# Generated by Django 5.0.6 on 2024-07-24 16:17

import post.models
from django.db import migrations, models


def gen_uid_for_posts(apps, schema_editor):
    Post = apps.get_model("post", "Post")

    for obj in Post.objects.all():
        obj.uid = post.models.generate_post_uid()
        obj.save(update_fields=["uid"])


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_alter_post_image_alter_post_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="uid",
            field=models.CharField(
                default=post.models.generate_post_uid, max_length=12
            ),
        ),

        migrations.RunPython(
            gen_uid_for_posts,
            migrations.RunPython.noop,
        ),

    ]
