# Generated by Django 5.0.6 on 2024-07-24 16:28

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_post_uid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="id",
        ),
        migrations.AlterField(
            model_name="post",
            name="uid",
            field=models.CharField(
                default=post.models.generate_post_uid,
                max_length=12,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
