# Generated by Django 5.0.6 on 2024-07-24 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_remove_post_id_alter_post_uid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="created_at",
            new_name="timestamp",
        ),
    ]
