# Generated by Django 5.0.6 on 2024-07-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_rename_created_at_post_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
